### ISSUE TITLE
Implement splitting securities into separate chunks

### ISSUE THREAD

**Issue by davclark** [dlab-projects/python-taq#2]
It makes sense to do this for performance reasons. We also want to store separate tables in HDF5 / pytables.

**Comment by davclark** [comment]
cc @juanshishido 

The logic for getting blocks of single securities is in `dlab-finance/basic-taq/stat_summary.py`.

**Comment by davclark** [comment]
Example of accumulator logic is in [this notebook](https://github.com/dlab-projects/dlab-finance/blob/master/basic-taq/Generator%20examples.ipynb).

**Comment by davclark** [comment]
cc @Jay4869

**Comment by davclark** [comment]
The core logic is now in a notebook in the tests directory.

**Comment by deniederhut** [comment]
@davclark Now that I'm looking at your notebook example, I'm worried that I've misremembered this conversation. Do we want a tool that chunks data by ticker symbol after it's already been read into memory? Or a tool that reads an entire chunk of a single ticker symbol into memory?

Or both?

**Comment by davclark** [comment]
I think the only way to do the second thing would be to read one line at a
time, which I think would be slow. The model would be:

chunk of N (e.g., 100000) rows -> chunks for each symbol

The remaining bit of logic is to hang on to the last symbol and make sure
it's combined with any data in subsequent chunks of N.

D

On Thu, Feb 11, 2016 at 4:17 PM, Dillon Niederhut <notifications@github.com>
wrote:

> @davclark <https://github.com/davclark> Now that I'm looking at your
> notebook example, I'm worried that I've misremembered this conversation. Do
> we want a tool that chunks data by ticker symbol after it's already been
> read into memory? Or a tool that reads an entire chunk of a single ticker
> symbol into memory?
>
> Or both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlab-projects/python-taq/issues/2#issuecomment-183121360>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408
